### ISSUE TITLE
Error when `license` contains an array

### ISSUE THREAD

**Issue by avdv** [FriendsOfShopware/FroshPluginUploader#118]
According to the composer schema (https://getcomposer.org/doc/04-schema.md#license), the `license` property may be a string or an array of strings.

Using `ext:validate` on a zip file with
```composer.json
...
    "license": [                                                                                                                               
        "proprietary"
    ]
...
```
fails:
```
Fatal error: Uncaught TypeError: strtolower() expects parameter 1 to be string, array given in phar:///home/claudio/src/silwy/shopware/custom/plugins/eXaFacebookConversions/frosh-plugin-upload.phar/src/Components/Generation/ShopwarePlatform/PluginReader.php:77
Stack trace:
#0 phar:///home/claudio/src/silwy/shopware/custom/plugins/eXaFacebookConversions/frosh-plugin-upload.phar/src/Components/Generation/ShopwarePlatform/PluginReader.php(77): strtolower(Array)
#1 phar:///home/claudio/src/silwy/shopware/custom/plugins/eXaFacebookConversions/frosh-plugin-upload.phar/src/Components/PluginValidator/General/LicenseValidation.php(19): FroshPluginUploader\Components\Generation\ShopwarePlatform\PluginReader->getLicense()
#2 phar:///home/claudio/src/silwy/shopware/custom/plugins/eXaFacebookConversions/frosh-plugin-upload.phar/src/Commands/ValidatePluginCommand.php(68): FroshPluginUploader\Components\PluginValidator\General\LicenseValidation->validate(Object(FroshPluginUploader\Structs\ViolationContext))
#3 phar:///home/claudio/src/s in phar:///home/claudio/src/silwy/shopware/custom/plugins/eXaFacebookConversions/frosh-plugin-upload.phar/src/Components/Generation/ShopwarePlatform/PluginReader.php on line 77
```

**Comment by shyim** [comment]
Hmm thats difficult now. The store supports only once. Soo considering only first?

**Comment by avdv** [comment]
> Hmm thats difficult now. The store supports only once. Soo considering only first?

Following the principle of least surprise, I would have accepted a single element array, otherwise display an error.

**Comment by shyim** [comment]
I have created an internal Ticket as this topic needs to be discussed in the Store context and adjusted here then. For know I would just choose the first one of the array
